spring.application.name=paperhub-chating

server.port=8888

spring.datasource.url=jdbc:mysql://localhost:3306/paperhub?useUnicode=true&characterEncoding=utf-8
spring.datasource.username=root
spring.datasource.password=20050106
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ??sql?? ??????
spring.jpa.show-sql=true

# ???sql?? ??????
spring.jpa.properties.hibernate.format_sql=true

# ?????????????????????
spring.jpa.hibernate.ddl-auto=update