# application.properties
spring.config.import=optional:classpath:application-local.properties

spring.application.name=paperhub

# MySQL datasource
spring.datasource.url=${DB_URL:jdbc:mysql://1.95.209.72:3306/paperhub}
spring.datasource.username=${DB_USERNAME:team}

# Hikari (optional but recommended)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
# Disable global identifier quoting
spring.jpa.properties.hibernate.globally_quoted_identifiers=false

# JWT
jwt.expires-in-seconds=1800
# Refresh Token expiration in seconds, default 7 days
jwt.refresh-expires-in-seconds=604800

# Mail
spring.mail.host=smtpdm.aliyun.com
spring.mail.port=465
spring.mail.username=${MAIL_USERNAME:paperhub@paperhub.icu}

spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.default-encoding=UTF-8

# ===== huawei OBS config =====
huawei.obs.endpoint=${HUAWEI_OBS_ENDPOINT:obs.cn-north-4.myhuaweicloud.com}
huawei.obs.bucketName=${HUAWEI_OBS_BUCKET:paperhub}

# Max single file size
spring.servlet.multipart.max-file-size=100MB
# Max request size
spring.servlet.multipart.max-request-size=100MB

# Redis config
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.database=0

# CORS
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:*}
